apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-node-deployment
spec:
  replicas: 2                                  # Number of pods
  selector:                                    #
    matchLabels:                               # This selector MUST MATCH below labels
      app: demo-node-deployment-label          #

  # Pod template
  template:
    metadata:
      labels:
        app: demo-node-deployment-label
    spec:
      containers:
        - name: demo-node-deployment
          image: thanh1669/demo-node-deployment
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: VERSION
              value: "1.0.0"
            - name: MESSAGE
              value: "Hello node deployment"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
